name: 테스트 검증

on:
  pull_request:

jobs:
  test-projects:
    name: 코드 테스트
    runs-on: ubuntu-latest
    steps:
      - name: 깃헙 레포지토리를 가져옵니다.
        uses: actions/checkout@v4

      - name: Node.js를 설치합니다.
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: 프로젝트를 설치합니다.
        run: npm ci

      - name: 린트를 실행합니다.
        run: npm run lint

      - name: 빌드를 실행합니다.
        run: npm run build
